INSERT INTO student (name, subject, age) VALUES ('Alice Johnson', 'History', 21);
INSERT INTO student (name, subject, age) VALUES ('Bob Williams', 'Mathematics', 20);
INSERT INTO student (name, subject, age) VALUES ('Charlie Brown', 'Physics', 22);
INSERT INTO student (name, subject, age) VALUES ('Diana Miller', 'Chemistry', 19);
INSERT INTO student (name, subject, age) VALUES ('Edward Davis', 'Biology', 21);
INSERT INTO student (name, subject, age) VALUES ('Fiona Wilson', 'English Literature', 20);
INSERT INTO student (name, subject, age) VALUES ('George White', 'Computer Science', 23);
INSERT INTO student (name, subject, age) VALUES ('Hannah Moore', 'Psychology', 21);
INSERT INTO student (name, subject, age) VALUES ('Ian Taylor', 'Art History', 20);
INSERT INTO student (name, subject, age) VALUES ('Jessica Anderson', 'Political Science', 22);
INSERT INTO student (name, subject, age) VALUES ('Olivia Parker', 'Sociology', 20);
INSERT INTO student (name, subject, age) VALUES ('Noah Carter', 'Economics', 22);
INSERT INTO student (name, subject, age) VALUES ('Sophia Lee', 'Environmental Science', 21);
INSERT INTO student (name, subject, age) VALUES ('Liam Hall', 'Mechanical Engineering', 23);
INSERT INTO student (name, subject, age) VALUES ('Ava King', 'Statistics', 20);
INSERT INTO student (name, subject, age) VALUES ('Mason Wright', 'Journalism', 22);
INSERT INTO student (name, subject, age) VALUES ('Isabella Lopez', 'Graphic Design', 19);
INSERT INTO student (name, subject, age) VALUES ('Jacob Scott', 'Aerospace Engineering', 24);
INSERT INTO student (name, subject, age) VALUES ('Mia Baker', 'Linguistics', 21);
INSERT INTO student (name, subject, age) VALUES ('Ethan Adams', 'Film Studies', 20);
INSERT INTO student (name, subject, age) VALUES ('Leo Thompson', 'Mathematics', 21);
INSERT INTO student (name, subject, age) VALUES ('Zoe Wilson', 'Mathematics', 20);